= SAÉ 3.01 2023-2024
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template



toc::[]

== Equipe

Projet réalisé par::

- https://github.com/PierreCornu[Pierre Cornu]
- https://github.com/RaphaLLamothe[Raphaël Lamothe]
- https://github.com/NariaReynhard[Naria Savary]
- https://github.com/DavidTRANMinhAnh[David Tran]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

== Contexte général

=== Présentation du client

SweetShops est une entreprise spécialisée dans la vente de confiseries et chocolats haut de gamme. Cette enseigne propose
une large gamme de produits tels que des bonbons ou encore des chocolats, ainsi que des boissons telles que des sodas et des thés glacés.
L'entreprise vise à exploiter le potentiel digital pour accroître sa visibilité et sa compétitivité afin d'attirer une clientèle plus large et de diversifier ses offres.

[[liensUtiles]]
=== Liens utiles

- Le cours https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

Afin de communiquer nous utilisons Discord.

== Réalisations 
Vous trouverez dans cette section toute les informations concernant les réalisations du projet.

=== Documentation de conception

Ce document traite des cas d’utilisation du site, il présentera également un diagramme des classes métiers ainsi qu’un diagramme des classes de conception, ce dernier axé sur les fonctionnalités de recherche, de visualisation et d’ajout au panier des produits proposés par le site.
Il est destiné à l’équipe de développement afin d’avoir une compréhension unique de l’architecture du site, ainsi qu’au client pour qu’il puisse visualiser comment ce dernier fonctionnera, et enfin à l’équipe pédagogique afin d’être évalué.

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/Documentation%20conception.adoc[Lien vers la documentation de conception]   
|=======

=== Documentations Technique
La documentation technique contiendra toutes les informations nécessaires pour comprendre et développer le projet. Elle détaille les composants techniques, les spécifications des fonctionnalités, et les exigences d’architecture, permettant aux développeurs d'avoir une vision complète et cohérente de l'infrastructure et des interactions du système. +

Une documentation technique de la partie administration du site sera fournie. Elle détaillera les fonctionnalités principales, les configurations possibles, ainsi que les instructions de maintenance et de résolution des problèmes courants, permettant ainsi une gestion autonome et efficace de la plateforme.

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/DocumentationTechniqueJava.adoc[Lien vers la documentation technique Java]   
|=======

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/DocumentationTechniquePython.adoc[Lien vers la documentation technique Python]   
|=======

=== Documentation utilisateur
La documentation utilisateur sera destinée pour les utilisateurs finaux, présentant de manière détaillée les fonctionnalités disponibles et leur utilisation. Ce document servira de guide pratique pour que les utilisateurs puissent naviguer et interagir facilement avec les différentes fonctionnalités de l'interface, leur assurant une expérience fluide et intuitive sur le site ou l'application. +

Pour accompagner les futurs administrateurs du site et faciliter leur prise en main, nous proposons une documentation utilisateur détaillée. Celle-ci comprendra des instructions claires pour naviguer et utiliser efficacement l'interface d'administration, ainsi qu'un guide pour la gestion des produits et des commandes. +

De plus, nous inclurons deux diagrammes de collaboration pour clarifier les processus clés : le premier diagramme illustrera le processus de création d’un produit (de l’ajout d’un nouveau produit à son affichage sur le site), tandis que le second décrira le suivi complet d'une commande (depuis la commande passée par un client jusqu'à la livraison). Ces diagrammes aideront à communiquer les étapes de chaque processus et à former les administrateurs plus facilement. +

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/Documentation%20conception.adoc[Lien vers la documentation de utilisateur]   
|=======

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/Documentation%20conception.adoc[Lien vers la documentation de administrateur]   
|=======

== Gestion de projet & Qualité

Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v1]

=== User Stories 

Les User Stories et leurs avancements seront dans le https://github.com/orgs/IUT-Blagnac/projects/253[Project Board] de ce repository. + 
Vous pourrez les voir triés via ce lien
https://github.com/orgs/IUT-Blagnac/projects/253/views/2[ici].

=== Tests unitaires et plans de test

Vous trouverez les testes unitaires https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/CahierDeRecette.adoc[ici].

=== Indicateurs de qualité du code (dette technique)

Vous trouverez les indicateurs de qualité (dette technique) ici.

=== Ordres du jours et comptes rendus de réunions

[cols="2*", options="header"]
|====
| Ordres du jour | Compte-rendus
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Ordre%20du%20jour/OrdreDuJour1.pdf[Semaine 44] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Compte%20Rendu/Compte%20Rendu1.pdf[Semaine 44]
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Ordre%20du%20jour/OrdreDuJour2.pdf[Semaine 45] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Compte%20Rendu/Compte%20Rendu2.pdf[Semaine 45] 
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Ordre%20du%20jour/OrdreDuJour3.pdf[Réunion avec SweetShops (Semaine 45)] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/CompteRenduReunionAvecClient/CompteRendu3.pdf[Réunion avec SweetShops (Semaine 45)]
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Ordre%20du%20jour/OrdreDuJour4.pdf[Semaine 46] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Compte%20Rendu/Compte%20Rendu%204.pdf[Semaine 46]
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Ordre%20du%20jour/OrdreDuJour5.pdf[Semaine 48] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Compte%20Rendu/CompteRendu5.pdf[Semaine 48]
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/SuiviAvancement/Ordre%20du%20jour/OrdreDuJour6.pdf[Semaine 49] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/tree/master/Documentation/CompteRenduReunionAvecClient[Semaine 48]
|====

== Retours et évaluations

[cols="5*", options="header"]
|====
| Semaine |Professeur| Nom | Retour | Note
| 48| EP  | retour Com  | ODJ : manque rôle qui anime, qui prend des notes ? Rubriques succintes, point client ? Qui est responsable de chaque rubrique ? Manque intitulé de la réunion. CR : trop succinct, chaque point doit être rédigé, manque analyse des difficultés:réussites. Manque retour réunion client, manque prochain responsable de l'organisation de la réunion semaine 49. | 1,2/3
|49 | EP|L'ODJ parle d'une réunion pour le 03/ 11, les thèmes ne sont pas à jour !! Pas de CR disponible pour la semaine 49.  Note : 0,2/3     Note appel Offre :11,64/20 (avec malus surnotation des autres équipes !)
 | 0,2/3|
| | | | |
| | | | |
| | | | |
|====



ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=2038500358&format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=2038500358&format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSACcYeKaH_ims3faegSLAFJ9s5_Kd9Fbyi4ODEb8BTN5OnUXWenVGhlVPo84yQDhTkTj3f9nXiluh1/pubchart?oid=2038500358&format=image"></iframe>
++++
endif::[]


