= SAÉ 3.01 2023-2024
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/fePVlfpN).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/PierreCornu[Pierre Cornu]
- https://github.com/RaphaLLamothe[Raphaël Lamothe]
- https://github.com/NariaReynhard[Naria Savary]
- https://github.com/DavidTRANMinhAnh[David Tran]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

== Contexte général

=== Présentation du client

SweetShope est une entreprise spécialisée dans la vente de confiseries et chocolats haut de gamme. Cette enseigne propose
une large gamme de produits tel que des bonbons ou encore des chocolats, ainsi que des boissons telles que des sodas et des thées glacés.
L'entreprise vise à expoiter le potentiel digital pou accroître sa visibilité et sa compétitivité afin d'attirer une clientèle plus large et de diversifier ses offres.

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

Afin de communiquer nous utilisons discord.

== Réalisations 
Vous trouverez dans cette section toute les informations concernant les réalisations du projet.

=== Documentation de conception

Ce document traite des cas d’utilisation du site, il présentera également un diagramme des classes métiers ainsi qu’un diagramme des classes de conceptions, ce dernier axé sur les fonctionnalité de recherche, de visualisation et d’ajout au panier des produits proposés par le site.
Il est destiné à l’équipe de développement afin d’avoir une compréhension unique de l’architecture du site, ainsi qu’au client pour qu’il puisse visualiser comment ce dernier fonctionnera, et enfin à l’équipe pédagogique afin d’être évalué.

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/Documentation%20conception.adoc[Lien vers la documentation de conception]   
|=======

=== Documentations Technique
La documentation technique contiendra toutes les informations nécessaires pour comprendre et développer le projet. Elle détaille les composants techniques, les spécifications des fonctionnalités, et les exigences d’architecture, permettant aux développeurs d'avoir une vision complète et cohérente de l'infrastructure et des interactions du système. +

Une documentation technique de la partie administration du site sera fournie. Elle détaillera les fonctionnalités principales, les configurations possibles, ainsi que les instructions de maintenance et de résolution des problèmes courants, permettant ainsi une gestion autonome et efficace de la plateforme.

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/Documentation%20conception.adoc[Lien vers la documentation technique utilisateur]   
|=======

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/Documentation%20conception.adoc[Lien vers la documentation technique administrateur]   
|=======

=== Documentation utilisateur
La documentation utilisateur sera destinée pour les utilisateurs finaux, présentant de manière détaillée les fonctionnalités disponibles et leur utilisation. Ce document servira de guide pratique pour que les utilisateurs puissent naviguer et interagir facilement avec les différentes fonctionnalités de l'interface, leur assurant une expérience fluide et intuitive sur le site ou l'application. +

Pour accompagner les futurs administrateurs du site et faciliter leur prise en main, nous proposons une documentation utilisateur détaillée. Celle-ci comprendra des instructions claires pour naviguer et utiliser efficacement l'interface d'administration, ainsi qu'un guide pour la gestion des produits et des commandes. +

De plus, nous inclurons deux diagrammes de collaboration pour clarifier les processus clés : le premier diagramme illustrera le processus de création d’un produit (de l’ajout d’un nouveau produit à son affichage sur le site), tandis que le second décrira le suivi complet d'une commande (depuis la commande passée par un client jusqu'à la livraison). Ces diagrammes aideront à communiquer les étapes de chaque processus et à former les administrateurs plus facilement. +

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/Documentation%20conception.adoc[Lien vers la documentation de utilisateur]   
|=======

[cols="1*", options="header"]
|=======
|  https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/Documentations/Documentation%20conception.adoc[Lien vers la documentation de administrateur]   
|=======

== Gestion de projet & Qualité

Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v1]

=== User Stories 

Les User Stories et leurs avancements seront dans le https://github.com/orgs/IUT-Blagnac/projects/253[Project Board] de ce repository. + 
Vous pourrez les voir triés via ce lien
https://github.com/orgs/IUT-Blagnac/projects/253/views/2[ici].

=== Tests unitaires et plans de test

Vous trouverez les testes unitaires ici.

=== Indicateurs de qualité du code (dette technique)

Vous trouverez les idicateurs de qualité (dette technique) ici.

=== Ordres du jours et comptes rendus de réunions

[cols="2*", options="header"]
|====
| Ordre du jours | Comptes rendus
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/19db97d3e239e70d570369820bfcb7a365fc2e69/Suivi%20de%20l'avancement/Ordre%20du%20jour/Ordredujour_1.pdf[Semaine 44] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/19db97d3e239e70d570369820bfcb7a365fc2e69/Suivi%20de%20l'avancement/Compte%20Rendu/Compte%20Rendu1.pdf[Semaine 44]
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/19db97d3e239e70d570369820bfcb7a365fc2e69/Suivi%20de%20l'avancement/Ordre%20du%20jour/Ordredujour2.pdf[Semaine 45] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/19db97d3e239e70d570369820bfcb7a365fc2e69/Suivi%20de%20l'avancement/Compte%20Rendu/Compte%20Rendu2.pdf[Semaine 45] 
| https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/19db97d3e239e70d570369820bfcb7a365fc2e69/Suivi%20de%20l'avancement/Ordre%20du%20jour/OrdreDuJour3.pdf[Réunion avec SweetShop (Semaine 45)] | https://github.com/IUT-Blagnac/sae-3-01-devapp-G1A-3/blob/master/Documentation/CompteRenduReunionAvecClient/CompteRendu3.pdf[Réunion avec SweetShop (Semaine 45)]
|  | 
|  | 
|  |
|====


== Retours et évaluations

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]

[cols="2*", options="header"]
|====
| Nom du retour  | Retour
|  | 
|  | 
|  | 
|  | 
|  | 
|====
