= Cahier de recette - Plateforme d'ecommerce - Sweetshops
:toc:
:toc-title: Sommaire
:Entreprise: LudoRama
:Equipe: LudoRama / G1A-3

== Présentation de l'application

L'application Java développée permet principalement à l'ensemble des utilisateurs de recueillir des données de différents capteurs.
De plus, il peut choisir quelles données recueillir parmi l'ensemble de celles récupérables, les seuils à partir desquels une alerte sera levée, et lancer le programme qui récupère les données.
L'affichage des données se fait de différentes manières : celles-ci sont soit affichées sous forme de graphes, soit sous forme de valeurs.
Cela permet à l'utilisateur de pouvoir avoir la donnée précise qu'il souhaite, ou autrement d'avoir une idée de comment les données ont varié durant une période donnée.

== Procédure d'installation

=== Pour le développement 
(comment installer l'environnement de développement)


== Pour le poste


== Use Case Global
(Expliquer le use case global)(types d'utilisateurs, spécificités...)


== Architecture 
=== Architecture générale 
(Architecture générale en terme de sous-systèmes et rôle de chaque élément : fichier de données, fichier de configuration, parties de l'application, ...)
=== Ressources externes utilisées et rôles
( API utilisées avec lien d'accès web + lien doc en ligne, ...)
=== Structuration en package de l'application 
(Structuration en packages de l’application documentée. Principes retenus pour cette structuration qui doivent être justifiés. Si des patterns particuliers sont utilisés (MVC, ...), les expliquer clairement.)
=== Élements essentiels 
(Eléments essentiels à connaître, spécificités, … nécessaires à la mise en œuvre du développement. Cette partie peut être illustrée par un diagramme de séquence. Par exemple, une structure récurrente de classes peut être décrite ici (contrôleurs de dialogues, contrôleurs de vue, …), les threads utilisés, ...)


== Fonctionnalités 

=== Package : src/main/java/
==== control
==== tools
==== view

=== Package : src/main/ressources/
Vu qu'il y a que les fxml, juste des screens et des explications si possibles.

